## Data types

In [1]:
import numpy as np

# float32
A=np.array([1,2,3],dtype='f4')
print('data type:',A.dtype)
print(A)

data type: float32
[1. 2. 3.]


In [2]:
# complex64
A=np.array([1+2j,3-4j],dtype='c8')
print('data type:',A.dtype)
print(A)

data type: complex64
[1.+2.j 3.-4.j]


In [6]:
# boolean
A=np.array([0,1,1],dtype=np.bool)
print('data type:',A.dtype)
print(A)

data type: bool
[False  True  True]


In [7]:
# String
A=np.array(['abcd','ABCD'],dtype='S3')
print('data type:',A.dtype)
print(A)

data type: |S3
[b'abc' b'ABC']


## Array

In [8]:
A=np.array(range(5))
A

array([0, 1, 2, 3, 4])

In [9]:
# int16
A=np.array([[1,2,3],[4,5,6]],dtype='i2')
print('data type:',A.dtype)
print(A)

data type: int16
[[1 2 3]
 [4 5 6]]


In [10]:
# Evenly spaced array
A=np.arange(0, 20, 2) # 0 to 20 with interval of 2
print('data type:',A.dtype)
print(A)

data type: int32
[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
# linspace
A=np.linspace(0,10,20) # 20 points b/w 0 to 10
print('data type:',A.dtype)
print(A)

data type: float64
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [13]:
# exclude endpoint and return setp size (linspace)
A,step=np.linspace(0,10,20,endpoint=False,retstep=True)
print('Step:',step)
print(A)

Step: 0.5
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [14]:
# array with random values
A=np.random.rand(3,3)
print('data type:',A.dtype)
print(A)

data type: float64
[[0.49202643 0.55111518 0.31557089]
 [0.29622728 0.66218333 0.76929387]
 [0.50328197 0.09967328 0.28127165]]


In [15]:
# array of zeros
A=np.zeros((2,3),dtype='i4')
print('data type:',A.dtype)
print(A)

data type: int32
[[0 0 0]
 [0 0 0]]


In [16]:
# array of zeros of same shape as other array
A=np.random.rand(3,3)
zeros=np.zeros_like(A)
print('Shape of A:',A.shape)
print('Shape of zeros:',zeros.shape)

Shape of A: (3, 3)
Shape of zeros: (3, 3)


In [17]:
# array of ones
ones=np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [19]:
# array of ones of same shape as other array
A=np.random.rand(3,3)
ones=np.ones_like(A)
print('Shape of A:',A.shape)
print('Shape of ones:',ones.shape)

Shape of A: (3, 3)
Shape of ones: (3, 3)


In [21]:
# arbitary values
A=np.empty((2,2))
print(A.dtype)

float64


In [23]:
# array of arbitary values of same shape as other array
A=np.random.rand(2,2)
arb=np.empty_like(A)
print('Shape of A:',A.shape)
print('Shape of arb val:',arb.shape)

Shape of A: (2, 2)
Shape of arb val: (2, 2)


In [24]:
# array of same values
A=np.full((2,3),5)
print('data type:',A.dtype)
A

data type: int32


array([[5, 5, 5],
       [5, 5, 5]])

In [26]:
# array of same values of same shape as other array
A=np.random.rand(2,2)
B=np.full_like(A,5)
B

array([[5., 5.],
       [5., 5.]])

In [27]:
# repeat each element of an array by specific number of times
A=[0,1,2]
print(np.repeat(A,3))

[0 0 0 1 1 1 2 2 2]


In [30]:
A=[[1,2],[3,4]]
print(np.repeat(A,[1,2],axis=0))

[[1 2]
 [3 4]
 [3 4]]


In [31]:
# repeat numbers
A=[0,1,2]
print(np.tile(A,3))

[0 1 2 0 1 2 0 1 2]


In [32]:
# repeat along specific axis
A=[0,1,2,3]
print(np.tile(A,(2,2)))

[[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]


In [34]:
# identity matrix along diagonal axis
I=np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
# identity matrix along diagonal offset
I=np.eye(5,k=1) # +ve shift at diagonal upward
I

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [36]:
# -ve shift at diagonal downward
I=np.eye(5,k=-2)
I

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [39]:
# extract diagonal values
A=np.random.rand(5,5)
print('A:',A)
print('Diagonal values:',np.diag(A))

A: [[0.52534329 0.48186265 0.09648138 0.63104723 0.43106197]
 [0.72391637 0.36235775 0.19854819 0.15838585 0.30354482]
 [0.71838203 0.45525884 0.35955767 0.61960015 0.82665988]
 [0.52714574 0.08656853 0.21241158 0.09748977 0.00486212]
 [0.20367484 0.45801223 0.52974018 0.84540343 0.28813605]]
Diagonal values: [0.52534329 0.36235775 0.35955767 0.09748977 0.28813605]


In [40]:
# create a matrix with specific diagonal values
A=np.diag([1,2,3,4])
A

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Info regarding Array

In [41]:
A=np.array([[1,2,3],[4,5,6]],dtype=np.int64)
A

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [42]:
# info
print(np.info(A))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2b80904d740
byteorder:  little
byteswap:  False
type: int64
None


In [43]:
# data type
print('data type:',A.dtype)

data type: int64


In [44]:
# shape
print('Shape:',A.shape)

Shape: (2, 3)


In [46]:
# length of array
print('length of A:',len(A))

length of A: 2


In [48]:
# dimension
print('Dimension:',A.ndim)

Dimension: 2


In [49]:
# Number of element
print('Size:',A.size)

Size: 6


In [50]:
# number of byte of each element within an array
print('Item size:',A.itemsize)

Item size: 8


In [51]:
# memory size in bytes
print('Bytes:',A.nbytes)

Bytes: 48


## Sampling

In [52]:
# setting seed
np.random.seed(40)

In [53]:
# random seed (Independent of global seed)
A=np.random.RandomState(320)
A.rand(5)

array([0.71435399, 0.2559666 , 0.99330929, 0.40069184, 0.70841185])

In [54]:
# random scaler value
print(np.random.rand())

0.4076870280802861


In [55]:
# 1D array
print(np.random.rand(4))

[0.05536604 0.78853488 0.28730518 0.45035059]


In [56]:
# 2D array
print(np.random.rand(3,3))

[[0.30391231 0.52639952 0.62381221]
 [0.77677546 0.68624165 0.98093886]
 [0.60081609 0.81396852 0.70864515]]


In [57]:
# randn (Standard normal distribution) (mean=0,var=1)
print(np.random.randn(3,3))

[[-1.01700702 -0.13369303 -0.4381855 ]
 [ 0.49344349 -0.19900912 -1.27498361]
 [ 0.29349415  0.10895031  0.03172679]]


In [59]:
# np.random.randint(low,high,size,dtype)
A=np.random.randint(1,20,5,'i8')
print('data type:',A.dtype)
print(A)

data type: int64
[ 3 19 13  6 17]


In [60]:
# random floating point numbers b/w 0 and 1
A=np.random.random_sample(5)
B=np.random.random(5)
C=np.random.ranf(5)
D=np.random.sample(5)

In [62]:
# random sample for 1D array
print(np.random.choice(range(3),10,replace=True,p=[0.1,0.8,0.1]))

[1 1 1 0 2 1 1 1 0 1]


In [67]:
print(np.random.choice([1,2,3],10))

[3 1 1 2 1 3 1 1 2 2]


In [70]:
# shuffle values in array
A=np.array(range(12))
np.random.shuffle(A)
print('Shuffle:',A)

Shuffle: [ 8  1  5  2  9  4  3 10  6  7  0 11]


In [71]:
# permutation of array (similar to shuffle)
A=np.array(range(10))
print('Initial array:',A)
print('Permutated array:',np.random.permutation(A))

Initial array: [0 1 2 3 4 5 6 7 8 9]
Permutated array: [0 6 5 7 8 9 2 3 4 1]


## Math Functions

In [73]:
A=np.random.rand(5)
print(A)

[0.34851137 0.91539995 0.85444843 0.9911576  0.36178449]


In [75]:
# elementwise add,sub,multiply,divide
print('Add:',A+5)
print('Sub:',A-5)
print('Multiply:',A*5)
print('Divide:',A/5)

Add: [5.34851137 5.91539995 5.85444843 5.9911576  5.36178449]
Sub: [-4.65148863 -4.08460005 -4.14555157 -4.0088424  -4.63821551]
Multiply: [1.74255685 4.57699975 4.27224216 4.95578802 1.80892244]
Divide: [0.06970227 0.18307999 0.17088969 0.19823152 0.0723569 ]


In [77]:
# elementwise add,sub,multiply
A=np.array([1,2,3])
B=np.array([2,3,4])
Add=np.add(A,B)
Sub=np.subtract(A,B)
Mul=np.multiply(A,B)
print('Add:',Add)
print('Sub:',Sub)
print('Mul:',Mul)

Add: [3 5 7]
Sub: [-1 -1 -1]
Mul: [ 2  6 12]


In [78]:
# elementwise exponential
A=np.random.randn(3)
exp=np.exp(A)
print('Exp:',exp)

Exp: [3.57026514 2.0026134  0.20212149]


In [82]:
# elementwise natural log
A=np.array([2,3,4])
log=np.log(A)
print('Log:',log)

Log: [0.69314718 1.09861229 1.38629436]


In [83]:
# Base 2 log
print('base2 log:',np.log2(A))

base2 log: [1.        1.5849625 2.       ]


In [84]:
# Base10 log
print('base10 log:',np.log10(A))

base10 log: [0.30103    0.47712125 0.60205999]


In [85]:
# sqrt
print('Sqrt:',np.sqrt(A))

Sqrt: [1.41421356 1.73205081 2.        ]


In [86]:
# sin and cosine
print('Sin:',np.sin(A))
print('Cosine:',np.cos(A))

Sin: [ 0.90929743  0.14112001 -0.7568025 ]
Cosine: [-0.41614684 -0.9899925  -0.65364362]


In [91]:
# sum 0f all element along certain axis
A=np.random.rand(3,3)
print('Sum along row:',np.sum(A,axis=0))
print('Sum along column:',np.sum(A,axis=1))

Sum along row: [0.32823917 2.17081946 0.91699284]
Sum along column: [1.18787758 0.8456466  1.38252729]


In [93]:
# max values along certain axis
print('max value along row:',np.max(A,axis=0))
print('max value along column:',np.max(A,axis=1))

max value along row: [0.22318183 0.95176601 0.54155675]
max value along column: [0.56437342 0.65468003 0.95176601]


In [94]:
# min values along certain axis
print('min value along row:',np.min(A,axis=0))
print('min value along column:',np.min(A,axis=1))

min value along row: [0.02310993 0.56437342 0.16785664]
min value along column: [0.08194741 0.02310993 0.20757945]


In [95]:
# min max values along entire matrix
print('Min value:',np.min(A))
print('Max value:',np.max(A))

Min value: 0.02310992624336672
Max value: 0.951766012365578


In [96]:
# Indices for min and max values along specific axis (row)
print('Indices for min values along row:',np.argmin(A,axis=0))
print('Indices for max values along row:',np.argmax(A,axis=0))

Indices for min values along row: [1 0 1]
Indices for max values along row: [2 2 0]


In [97]:
# Indices for min and max values along specific axis (column)
print('Indices for min values along column:',np.argmin(A,axis=1))
print('Indices for max values along column:',np.argmax(A,axis=1))

Indices for min values along column: [0 0 2]
Indices for max values along column: [1 1 1]


In [98]:
# Indices for min and max values along entire matrix
print('min value indice:',np.argmin(A))
print('max value indice:',np.argmax(A))

min value indice: 3
max value indice: 7


In [99]:
# elementwise min and max of 2 arrays
A=np.array([1,2,3,4])
B=np.array([2,3,4,5])
print('Min:',np.minimum(A,B))
print('Max:',np.maximum(A,B))

Min: [1 2 3 4]
Max: [2 3 4 5]


In [100]:
# split integral and floating values
A=np.random.rand(10)*5
Fr,integ=np.modf(A)
print('Fractional part:',Fr)
print('Integral part:',integ)

Fractional part: [0.6624271  0.92461996 0.7852692  0.32868608 0.47753847 0.21841289
 0.38999551 0.62259913 0.35038991 0.06046123]
Integral part: [3. 4. 3. 0. 4. 4. 2. 4. 1. 4.]


In [103]:
# mean value
A=np.random.rand(3,3)
print('Mean value:',np.mean(A))

Mean value: 0.28778259387956434


In [104]:
# mean value along row and column
print('Mean values along row:',np.mean(A,axis=0))
print('Mean values along column:',np.mean(A,axis=1))

Mean values along row: [0.16115371 0.21871191 0.48348216]
Mean values along column: [0.28826134 0.34321848 0.23186796]


In [105]:
# median value
A=np.random.rand(3,3)
print('Median value:',np.median(A))

Median value: 0.37161733206260106


In [106]:
# median value along row and column
print('Median values along row:',np.median(A,axis=0))
print('Median values along column:',np.median(A,axis=1))

Median values along row: [0.36163601 0.37161733 0.5523528 ]
Median values along column: [0.37458818 0.37161733 0.36163601]


In [109]:
# compute percentile
A=np.random.rand(10)
print('Values at 3,5,7:',np.percentile(A,[3,5,7]))

Values at 3,5,7: [0.27209613 0.27297723 0.27385834]


In [110]:
# Standard deviation
A=np.random.rand(3,3)
print('SD:',np.std(A))
print('SD along row:',np.std(A,axis=0))
print('SD along column:',np.std(A,axis=1))

SD: 0.20415857483969557
SD along row: [0.00947044 0.30909266 0.10091677]
SD along column: [0.06205065 0.23979539 0.15096486]


In [111]:
# Variance
A=np.random.rand(3,3)
print('Var:',np.var(A))
print('Var along row:',np.var(A,axis=0))
print('Var along column:',np.var(A,axis=1))

Var: 0.04855240349769328
Var along row: [0.02862826 0.01649981 0.03187268]
Var along column: [0.03401616 0.08715769 0.0084689 ]


In [115]:
# covariance and correlation
A=np.random.rand(3,3)
print('covariance:',np.cov(A))
print('correlation:',np.corrcoef(A[:,0],A[:,1]))

covariance: [[ 0.08112639 -0.01891915  0.02149096]
 [-0.01891915  0.05610863  0.05877528]
 [ 0.02149096  0.05877528  0.08439841]]
correlation: [[1.         0.51174043]
 [0.51174043 1.        ]]


In [117]:
# cumulative sum
print('cumulative value:',np.cumsum(A))
print('cumulative value along x-axis:',np.cumsum(A,axis=0))
print('cumulative value along y-axis:',np.cumsum(A,axis=1))

cumulative value: [0.10156193 0.68181799 0.75529825 1.18848084 1.75653497 2.65045109
 2.69979671 3.18010915 3.78242288]
cumulative value along x-axis: [[0.10156193 0.58025606 0.07348027]
 [0.53474451 1.1483102  0.96739638]
 [0.58409013 1.62862264 1.56971011]]
cumulative value along y-axis: [[0.10156193 0.68181799 0.75529825]
 [0.43318258 1.00123672 1.89515284]
 [0.04934562 0.52965806 1.13197179]]


In [118]:
# cumulative product
print('cumulative product value:',np.cumprod(A))
print('cumulative product value along x-axis:',np.cumprod(A,axis=0))
print('cumulative product value along y-axis:',np.cumprod(A,axis=1))

cumulative product value: [1.01561929e-01 5.89319247e-02 4.33033346e-03 1.87582503e-03
 1.06557017e-03 9.52530347e-04 4.70031969e-05 2.25762206e-05
 1.35979676e-05]
cumulative product value along x-axis: [[0.10156193 0.58025606 0.07348027]
 [0.04399486 0.32961685 0.06568519]
 [0.00217095 0.15831908 0.03956309]]
cumulative product value along y-axis: [[0.10156193 0.05893192 0.00433033]
 [0.43318258 0.24607116 0.21996697]
 [0.04934562 0.02370131 0.01427563]]


In [120]:
# element wise comparision
A=np.array([1,2,3,4])
B=np.array([2,3,4,5])
print('A==B:',A==B)
print('A<3:',A<3)

A==B: [False False False False]
A<3: [ True  True False False]


## Slicing

In [121]:
A=np.array(range(100)).reshape(10,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
A[5][5] # A[5,5]

55

In [124]:
print(A[1:4,3:6])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [128]:
# ellipsis slicing
A=np.array(range(16)).reshape(2,2,2,2)
print(A[0,...])
print(A[1,...])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [129]:
# assigning a value to a slice by broadcasting
A=np.array(range(100)).reshape(10,10)
A[1:3,:]=100
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [130]:
# boolean indexing
A=np.arange(25).reshape(5,5)
bools=np.array([True,True,False,True,False])
print(A[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [131]:
# negate the condition
print(A[~bools])

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [132]:
A=np.arange(25).reshape(5,5)
B=np.array([1,2,3,4,5])
print(A[(B<2) | (B>4)])

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


In [133]:
# indexing
A=np.random.rand(10,10)
print(A[[3,1,2],[3,2,1]]) # A[3,3],A[1,2],A[2,1]

[0.20087971 0.40729391 0.74725083]


In [134]:
# row 3,1,2 and column 6,4,8
print(A[[3,1,2]][:,[6,4,8]])

[[0.46664625 0.75013747 0.4810503 ]
 [0.31295532 0.21937439 0.15382818]
 [0.08064292 0.75443964 0.32296719]]


In [135]:
# dimention inference
A=np.array(range(16)).reshape(4,-1)
print(A.shape)

(4, 4)


In [136]:
# find element greater than 5 and return a flatten array
A=np.arange(16).reshape(4,4)
print(A[A>5]) # or A[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [138]:
# return values depending on condition
# np.where(condition,true,false)
print(np.where(A>5,-1,2))

[[ 2  2  2  2]
 [ 2  2 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [139]:
# find indices where element satisfies condition
print(np.argwhere(A>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


## Sorting

In [140]:
A=np.random.rand(5,5)
print(np.sort(A,axis=0)) # along row axis

[[0.26858101 0.04471807 0.11882602 0.09450724 0.55439209]
 [0.51181643 0.19195597 0.30944202 0.37339786 0.7939121 ]
 [0.77630382 0.28252082 0.31715859 0.41424364 0.85441524]
 [0.84897918 0.5515854  0.32053122 0.63643205 0.90210982]
 [0.95682905 0.94970314 0.39688193 0.72981917 0.99153762]]


In [141]:
# sort along column axis
print(np.sort(A,axis=1))

[[0.30944202 0.41424364 0.5515854  0.55439209 0.84897918]
 [0.04471807 0.09450724 0.11882602 0.95682905 0.99153762]
 [0.28252082 0.32053122 0.72981917 0.77630382 0.90210982]
 [0.19195597 0.39688193 0.51181643 0.63643205 0.85441524]
 [0.26858101 0.31715859 0.37339786 0.7939121  0.94970314]]


In [142]:
# compute indices for sorted data
A=np.random.rand(5,5)
print('Indices along x-axis',np.argsort(A,axis=0))
print('Indices along y-axis',np.argsort(A,axis=1))

Indices along x-axis [[4 0 2 4 2]
 [3 1 4 1 0]
 [0 4 1 0 1]
 [2 2 3 2 3]
 [1 3 0 3 4]]
Indices along y-axis [[4 1 0 3 2]
 [4 1 3 2 0]
 [4 2 0 1 3]
 [0 4 2 1 3]
 [3 2 0 1 4]]


In [143]:
print(np.argsort(A,axis=None))

[14  4  1 23 12  9  6 22 20 15  8 21  7 19  0 17 10 11 16  5  3  2 13 24
 18]


## Manipulating an array

In [145]:
# transpose
A=np.random.rand(3,2)
B=A.T
print('Shape of A:',A.shape)
print('Shape of B:',B.shape)
B

Shape of A: (3, 2)
Shape of B: (2, 3)


array([[0.97415732, 0.69281843, 0.32662029],
       [0.20322947, 0.04585377, 0.01024053]])

In [146]:
# transpose high dimensional array
A=np.arange(16).reshape(2,2,4)
B=A.transpose((1,0,2))
print(A.shape)
print(B.shape)
B

(2, 2, 4)
(2, 2, 4)


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [147]:
# swap axes
A=np.arange(16).reshape((2,2,4))
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [148]:
print(A.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [152]:
# shape of array
A=np.arange(12).reshape((4,3))
B=A.reshape((2,6))
B

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [153]:
# flatten
A=np.arange(16).reshape(4,4)
B=A.flatten()
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [154]:
C=A.ravel()
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
# appending elements in array
A=np.array([1,2,3,4])
B=np.append(A,[5,6])
B

array([1, 2, 3, 4, 5, 6])

In [158]:
# replace elements in array
A=np.array([1,2,3,4])
B=np.insert(A,2,100)
B

array([  1,   2, 100,   3,   4])

In [159]:
# delete element in an array
A=np.array([1,2,3])
B=np.delete(A,0)
B

array([2, 3])

In [160]:
A=np.array([1,2,3,4,5,6])
B=np.delete(A,[1,3])
B

array([1, 3, 5, 6])

In [161]:
# copy array
A=np.array([1,2,3,4])
B=A.copy()
B

array([1, 2, 3, 4])

## Splitting 

In [162]:
A=np.array([[1,2,3,4],[1,2,3,4]])
B=np.array([[5,6,7,8],[5,6,7,8]])

In [163]:
# concatenate along row
C=np.concatenate((A,B),axis=0)
C

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [164]:
# concatenate along column
D=np.concatenate((A,B),axis=1)
D

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [166]:
# stack vertically
E=np.vstack((A,B))
E

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [167]:
# stack horizontally
F=np.hstack((A,B))
F

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [174]:
# horizontal split
A=np.arange(16).reshape(4,4)
B=np.hsplit(A,2)
print('Shape of A:',A.shape)
print('Shape of B[0]:',B[0].shape)
print('Shape of B[1]:',B[1].shape)
B

Shape of A: (4, 4)
Shape of B[0]: (4, 2)
Shape of B[1]: (4, 2)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [176]:
# vertical split
A=np.arange(16).reshape(4,4)
B=np.vsplit(A,2)
print('Shape of A:',A.shape)
print('Shape of B[0]:',B[0].shape)
print('Shape of B[1]:',B[1].shape)
B

Shape of A: (4, 4)
Shape of B[0]: (2, 4)
Shape of B[1]: (2, 4)


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## Set Operation

In [177]:
# unique element in array
A=np.array([1,1,2,2,3,3,3,4,5,5,5,5,6])
print('unique values:',np.unique(A))

unique values: [1 2 3 4 5 6]


In [178]:
# return value and number of repeats
uniques,counts=np.unique(A,return_counts=True)
print('unique values:',uniques)
print('Counts:',counts)

unique values: [1 2 3 4 5 6]
Counts: [2 2 3 1 4 1]


In [179]:
# intersection over union
A=np.array([1,2,3,4,5])
B=np.array([3,4,5,6,7])
# intersection
print('Intersection:',np.intersect1d(A,B))

# union
print('Union:',np.union1d(A,B))

Intersection: [3 4 5]
Union: [1 2 3 4 5 6 7]


In [180]:
print(np.in1d(A,B))

[False False  True  True  True]


In [181]:
# compute elements in array that are not in another array
print(np.setdiff1d(A,B))

[1 2]


## Linear Algebra

In [182]:
# matrix multiplication (elementwise)
A=np.random.rand(3,3)
B=np.random.rand(3,3)
print(A@B)
#print(np.dot(A,B))

[[0.68319781 0.79189007 0.86662303]
 [0.98964456 0.82067095 1.17205628]
 [0.63086592 0.47839704 0.8428932 ]]


In [183]:
# QR factorization
A=np.random.rand(5,5)
q,r=np.linalg.qr(A)
print('Q:',q)
print('R:',r)

Q: [[-0.03412506 -0.04824168 -0.91355179  0.33269527 -0.22637405]
 [-0.15622317 -0.58763827  0.31493719  0.72674882 -0.05409524]
 [-0.10425878 -0.62150154 -0.25442751 -0.367432    0.63492229]
 [-0.37211967 -0.39231369  0.03826771 -0.46585199 -0.69938146]
 [-0.90834292  0.33493253 -0.00631848  0.0955283   0.2314471 ]]
R: [[-1.05910828 -1.28817529 -0.81603678 -1.34277088 -1.14445072]
 [ 0.         -1.22358792 -0.21774571 -1.00021358 -0.99463668]
 [ 0.          0.         -0.52212653 -0.39377424  0.16984652]
 [ 0.          0.          0.          0.38913049  0.24060606]
 [ 0.          0.          0.          0.          0.03884668]]


In [184]:
# single value decomposition (SVD)
A=np.random.rand(5,5)
u,s,v=np.linalg.svd(A)
print('u:',u)
print('s:',s)
print('v:',v)

u: [[-0.50840486  0.0440782  -0.70776199  0.48838599 -0.01156302]
 [-0.40698488 -0.59232143 -0.08324933 -0.47908387  0.49705818]
 [-0.3237877  -0.49981342  0.55673114  0.50828491 -0.27756973]
 [-0.53180439  0.23985993  0.05616708 -0.50878414 -0.63058327]
 [-0.43385876  0.58298045  0.42312907  0.12142042  0.52737012]]
s: [2.57062086 0.90555547 0.41075454 0.37680754 0.19014749]
v: [[-0.55598737 -0.50168334 -0.4388972  -0.38661448 -0.31159325]
 [ 0.03100374 -0.26157959  0.59066525  0.21426199 -0.73199812]
 [-0.35839482  0.10731319  0.64707352 -0.59559731  0.29427323]
 [ 0.58843709 -0.71184607  0.08900722 -0.24803241  0.27852217]
 [-0.46390921 -0.40205596  0.1784864   0.62318922  0.45046316]]


In [185]:
# compute eigen values
A=np.random.rand(5,5)
print(np.linalg.eigvals(A))

[ 2.70825462 -0.9061212   0.28089081  0.49143096  0.66654835]


In [186]:
# eigen value decomposition
A=np.random.rand(5,5)
w,v=np.linalg.eig(A)
print('w(eigen value):',w)
print('v(eigen vector):',v)

w(eigen value): [ 2.48690289+0.j          0.02563825+0.57329488j  0.02563825-0.57329488j
 -0.38464629+0.14385146j -0.38464629-0.14385146j]
v(eigen vector): [[-0.54210134+0.j         -0.19216698+0.1430697j  -0.19216698-0.1430697j
   0.24806273+0.20212485j  0.24806273-0.20212485j]
 [-0.3403483 +0.j         -0.0080994 +0.49809658j -0.0080994 -0.49809658j
  -0.33020294+0.03454123j -0.33020294-0.03454123j]
 [-0.34285292+0.j         -0.23142767-0.10588127j -0.23142767+0.10588127j
   0.00120804-0.22936374j  0.00120804+0.22936374j]
 [-0.57028683+0.j          0.02068878-0.52762345j  0.02068878+0.52762345j
  -0.57116639-0.10614856j -0.57116639+0.10614856j]
 [-0.38407549+0.j          0.59232842+0.j          0.59232842-0.j
   0.63029803+0.j          0.63029803-0.j        ]]


In [188]:
# trace and determinant
A=np.random.rand(5,5)
print('Trace:',np.trace(A))
print('Determinant:',np.linalg.det(A))

Trace: 0.8839418438106326
Determinant: 0.05012685667028006


In [189]:
# inverse of matrix
A=np.random.rand(4,4)
print(np.linalg.inv(A))

[[ 7.80282826 -8.93275836  3.25248074 -0.16954065]
 [-6.06833689  8.85012957 -3.41237149 -0.25408436]
 [-3.36069492  2.14651495  0.78335684  0.22566228]
 [-2.7985683   3.74079802 -2.10992117  1.11573526]]


In [190]:
# psudo inverse 
print(np.linalg.pinv(A))

[[ 7.80282826 -8.93275836  3.25248074 -0.16954065]
 [-6.06833689  8.85012957 -3.41237149 -0.25408436]
 [-3.36069492  2.14651495  0.78335684  0.22566228]
 [-2.7985683   3.74079802 -2.10992117  1.11573526]]


In [191]:
# least square 
A=np.random.rand(5,5)
B=[1,2,3,4,5]
solution,residuals,rank,singular=np.linalg.lstsq(A,B)
print('solution:',solution)
print('residuals:',residuals)
print('rank:',rank)
print('singular:',singular)

solution: [ -5.39367214  15.64085556 -16.71082133  -9.49416751  26.85463558]
residuals: []
rank: 5
singular: [2.98679505 1.27970893 0.61582872 0.27337232 0.03192271]


C:\Users\User\AppData\Local\Temp\ipykernel_11492\1760653798.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution,residuals,rank,singular=np.linalg.lstsq(A,B)
